#!/bin/bash
#
# Shell script to start the Docker Docker image.
#
# Copyright 2020, Tarbase. All Rights Reserved
#   Author: Frederico Martins <http://github.com/fscm>
#

set -e

if ! [ -z "$1" ]; then
  exec "$@"
  exit 0
fi

echo "[INFO] Starting Docker daemon..."
# start dockerd
dockerd \
  --host="unix:///var/run/docker.sock" \
  --host='tcp://0.0.0.0:2375'

exit 0
