#!/bin/bash
#
# Shell script to test the Docker Docker image.
#
# Copyright 2020, Tarbase. All Rights Reserved
#   Author: Frederico Martins <http://github.com/fscm>
#

echo -n "=== TEST === Check if Docker is installed... "
if docker --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 1
fi

echo -n "=== TEST === Check if Docker daemon is installed... "
if dockerd --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 1
fi

echo -n "=== TEST === Check if docker-compose is installed... "
if docker-compose --version > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 3
fi

echo -n "=== TEST === Start the Docker daemon... "
dockerd --host="unix:///var/run/docker.sock" --pidfile '/var/run/docker.pid' > /dev/null 2>&1 &
sleep 10
if [ -f '/var/run/docker.pid' ]; then
  echo 'OK'
else
  echo 'Failed'
  exit 4
fi

echo -n "=== TEST === Connect to Docker daemon... "
if docker container ls > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 5
fi

echo -n "=== TEST === Pull a Docker image... "
if (docker pull fscm/centos:latest && docker image ls | grep -q '^fscm/centos.*latest') > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 6
fi

echo -n "=== TEST === Stop the Docker daemon... "
if kill -2 "$(cat /var/run/docker.pid)"  > /dev/null 2>&1; then
  echo 'OK'
else
  echo 'Failed'
  exit 8
fi

exit 0
